# Generated by Django 4.2.7 on 2025-04-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurukh_text', models.TextField()),
                ('hindi_translation', models.TextField()),
            ],
        ),
    ]
